//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> MaskSizeID { get; set; }
        public Nullable<int> MaskTypeID { get; set; }
        public Nullable<int> MachineTypeID { get; set; }
        public int StockStatusID { get; set; }
        public Nullable<bool> IsReplacement { get; set; }
        public int UnitsAvailable { get; set; }
        public Nullable<int> UnitsOnOrder { get; set; }
    
        public virtual MachineType MachineType { get; set; }
        public virtual MaskSize MaskSize { get; set; }
        public virtual MaskType MaskType { get; set; }
        public virtual Product Product { get; set; }
        public virtual StockStatu StockStatu { get; set; }
    }
}
