//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> MaskSizeID { get; set; }
        public int StockStatusID { get; set; }
        public int UnitsAvailable { get; set; }
        public Nullable<int> MaskTypeID { get; set; }
        public Nullable<int> MachineTypeID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public int CategoryID { get; set; }
        public int ManufacturerID { get; set; }
        public bool IsFeatured { get; set; }
    
        public virtual MaskSize MaskSize { get; set; }
        public virtual StockStatu StockStatu { get; set; }
        public virtual MachineType MachineType { get; set; }
        public virtual MaskType MaskType { get; set; }
        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
    }
}
